apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: thanos-operator
        app.kubernetes.io/instance: controller-manager-sa
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: serviceaccount
        app.kubernetes.io/part-of: thanos-operator
    name: thanos-operator-controller-manager
    namespace: {{ .Release.Namespace }}
