apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: thanos-operator
        app.kubernetes.io/instance: manager-rolebinding
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: clusterrolebinding
        app.kubernetes.io/part-of: thanos-operator
    name: thanos-operator-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: thanos-operator-manager-role
subjects:
    - kind: ServiceAccount
      name: thanos-operator-controller-manager
      namespace: {{ .Release.Namespace }}
