apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosQuery
metadata:
  name: example-query
spec:
  customStoreLabelSelector:
    matchLabels:
      operator.thanos.io/store-api: "true"
  imagePullPolicy: IfNotPresent
  labels:
    some-label: xyz
  logFormat: logfmt
  queryFrontend:
    compressResponses: true
    imagePullPolicy: IfNotPresent
    labelsMaxRetries: 3
    logFormat: logfmt
    logQueriesLongerThan: 10s
    queryLabelSelector:
      matchLabels:
        operator.thanos.io/query-api: "true"
    queryRangeMaxRetries: 3
    replicas: 2
  replicaLabels:
  - prometheus_replica
  - replica
  - rule_replica
  replicas: 1
status:
  querierStatus:
    availableReplicas: 0
    readyReplicas: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
  queryFrontendStatus:
    availableReplicas: 0
    readyReplicas: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
