{{- if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/created-by: thanos-operator
        app.kubernetes.io/instance: controller-manager-metrics-monitor
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: servicemonitor
        app.kubernetes.io/part-of: thanos-operator
        control-plane: controller-manager
    name: thanos-operator-controller-manager-metrics-monitor
    namespace: {{ .Release.Namespace }}
spec:
    endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          path: /metrics
          port: https
          scheme: HTTPS
          tlsConfig:
            ca: {}
            cert: {}
            insecureSkipVerify: true
    namespaceSelector: {}
    selector:
        matchLabels:
            control-plane: controller-manager
{{- end }}
