{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/component: kube-rbac-proxy
        app.kubernetes.io/created-by: thanos-operator
        app.kubernetes.io/instance: controller-manager-metrics-service
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: service
        app.kubernetes.io/part-of: thanos-operator
        control-plane: controller-manager
    name: thanos-operator-controller-manager-metrics-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https
          port: {{ .Values.metrics.port }}
          protocol: TCP
          targetPort: https
    selector:
        control-plane: controller-manager
status:
    loadBalancer: {}
{{- end }}
